#Zenityの練習用 ( ◜ᴗ◝)<ムギュルッパープエールが好きな人のみ使うように。
sudo zenity --entry --title "( ◜ᴗ◝)<ムギュルッパープエール" --text "( ◜ᴗ◝)<ムギュルッパープエール" --entry "( ◜ᴗ◝)<ムギュルッパープエール"
sudo zenity --entry --title "( ◜ᴗ◝)<ムギュルッパープエール" --text "( ◜ᴗ◝)<ムギュルッパープエール" --entry "( ◜ᴗ◝)<ムギュルッパープエール"
sudo zenity --entry --title "( ◜ᴗ◝)<ムギュルッパープエール" --text "( ◜ᴗ◝)<ムギュルッパープエール" --entry "( ◜ᴗ◝)<ムギュルッパープエール"
sudo zenity --entry --title "( ◜ᴗ◝)<ムギュルッパープエール" --text "( ◜ᴗ◝)<ムギュルッパープエール" --entry "( ◜ᴗ◝)<ムギュルッパープエール"
sudo zenity --entry --title "( ◜ᴗ◝)<ムギュルッパープエール" --text "( ◜ᴗ◝)<ムギュルッパープエール" --entry "( ◜ᴗ◝)<ムギュルッパープエール"
sudo zenity --entry --title "( ◜ᴗ◝)<ムギュルッパープエール" --text "( ◜ᴗ◝)<ムギュルッパープエール" --entry "( ◜ᴗ◝)<ムギュルッパープエール"
sudo zenity --entry --title "( ◜ᴗ◝)<ムギュルッパープエール" --text "( ◜ᴗ◝)<ムギュルッパープエール" --entry "( ◜ᴗ◝)<ムギュルッパープエール"
sudo zenity --entry --title "( ◜ᴗ◝)<ムギュルッパープエール" --text "( ◜ᴗ◝)<ムギュルッパープエール" --entry "( ◜ᴗ◝)<ムギュルッパープエール"
sudo zenity --entry --title "( ◜ᴗ◝)<ムギュルッパープエール" --text "( ◜ᴗ◝)<ムギュルッパープエール" --entry "( ◜ᴗ◝)<ムギュルッパープエール"
sudo zenity --entry --title "( ◜ᴗ◝)<ムギュルッパープエール" --text "( ◜ᴗ◝)<ムギュルッパープエール" --entry "( ◜ᴗ◝)<ムギュルッパープエール"
