echo "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"""""??????7"T""HMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"
echo "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMY"^`                         ?""MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"
echo "MMMMMMMMMMMMMMMMMMMMMMMMM#"`                                             ?WMMMMMMMMMMMMMMMMMMMMMMMMM"
echo "MMMMMMMMMMMMMMMMMMMMMM#=                                                    (TMMMMMMMMMMMMMMMMMMMMMM"
echo "MMMMMMMMMMMMMMMMMMMM"                                                          ?WMMMMMMMMMMMMMMMMMMM"
echo "MMMMMMMMMMMMMMMMM#'                                      `  `                     TMMMMMMMMMMMMMMMMM"
echo "MMMMMMMMMMMMMMM@`               `  `        `  `     `         `  `                 TMMMMMMMMMMMMMMM"
echo "MMMMMMMMMMMMMB!                     .......................................           TMMMMMMMMMMMMM"
echo "MMMMMMMMMMMM^               `       ..~.~.~..~..~.~...~..~..~......~.~.~.~.            .HMMMMMMMMMMM"
echo "MMMMMMMMMMD                    `    ...~...~.....~..~...~....~.~.~......~..              ?MMMMMMMMMM"
echo "MMMMMMMMM3            `  `    ......~~~~~~~~~~:~~~~~~:~~~~:~~~~~~~~~::.....               ,MMMMMMMMM"
echo "MMMMMMMM'                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~.~..~       `         WMMMMMMM"
echo "MMMMMM#`        `  `        ` ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~:..~..                  UMMMMMM"
echo "MMMMM#`                       __________________________________~~~~~~.....          `        UMMMMM"
echo "MMMMM!                  ~.~.~..~.~..~..~..~..~.~..~..~..~.~...~<~~~~~:.~.~.     `              WMMMM"
echo "MMMM^        `  `   `   .~.~.~.~..~..~.~.~.~..~.~.~.~.~.~..~~..<~~~~~~..~..             `      .MMMM"
echo "MMMF                    ~..~..~.~~.~.~.~..~.~~..~.~..~.~.~.~.~.<~~~~~~.....       `  `     `    ,MMM"
echo "MM#       `             .~..~~..~..~..~.~.~.~.~..~.~.~..~.~..~.<~~~~~:.~..~    `                 dMM"
echo "MMt            `  `     .~~.~.~..~~.~.~~.~..~..~~.~.~.~.~..~..~<~~~~~~..~..                      .MM"
echo "MM                      ~..~..~~.~..~..~..~.~.~..~.~.~.~.~.~~..<~~~~~~...~.            `  `       dM"
echo "MF       `  `           ..~.~..~.~.~.~.~.~.~.~.~..~..~..~.~..~.<~~.~~~~....      `  `        `    ,M"
echo "M%    `            `    ~.~.~~..~.~.~.~.~.~.~..~~.~.~.~.~..~.~.<~~~~~~.~...                       .M"
echo "M:             `        .~..~.~..~..~..~..~.~.~..~.~.~.~.~.~..~<~~~~~~.~.~.                     `  M"
echo "M         `             .~.~..~~.~.~.~.~.~.~.~.~..~.~..~..~.~..<~~~~~~....~     `     `  `  `      d"
echo "M    `            `     ~.~.~..~.~..~.~.~..~..~.~.~..~.~~.~.~..<~~~~~:..~..        `               d"
echo "M             `         ..~.~~..~.~.~..~.~~.~..~.~.~.~...~.~.~.<~~.~~~.~...                    `   d"
echo "M:      `  `            ~..~..~.~..~.~.~..~.~~.~..~.~.~.~..~..~<~~~~~~...~.                        M"
echo "M]                 `    .~.~.~.~.~.~..~.~..~..~.~.~..~.~.~~.~..<~~~~~~~...~    `  `    `   `      .M"
echo "Mb              `       ~.~.~.~.~.~.~.~~.~.~.~.~.~.~.~..~..~.~.<~~~~~~.~...                   `   .M"
echo "MN.  `                  ..~.~..~.~.~.~..~.~.~..~..~.~.~.~..~..~<~.~~~~..~..                       dM"
echo "MM]      `              ~..~.~..~..~..~..~..~.~.~.~..~.~.~~.~..<~~~~~~.~...        `   `   `     .MM"
echo "MMN.          `     `   .~.~.~~.~.~.~.~~.~.~.~.~.~.~~..~..~.~.~<~~~~~~..~..                      JMM"
echo "MMMb       `     `      .~..~..~.~.~.~..~.~.~.~..~..~.~.~..~.~.<~~~~~_`````     `             ` .MMM"
echo "MMMM,                   ~.~.~.~..~..~.~..~..~..~~.~..~.~.~..~..<~~.~~_                  `      .MMMM"
echo "MMMMN,  `               ..~~.~.~.~~..~.~.~.~.~..~.~~.~..~.~~..~<~~~~~_             `           dMMMM"
echo "MMMMMN.                 .~..~..~..~.~.~.~.~.~.~..~..~.~.~..~.~.~_____`                     `  JMMMMM"
echo "MMMMMMN.      `  `      ~.~.~.~.~~.~.~.~..~.~.~~.~.~.~.~.~..~.~                `      `      JMMMMMM"
echo "MMMMMMMN,           `   .~.~.~..~..~..~.~..~.~..~.~.~..~.~~.~..                   `        .dMMMMMMM"
echo "MMMMMMMMM,              ..~.~.~..~..~..~.~~.~..~..~..~..~..~.~~             `             .MMMMMMMMM"
echo "MMMMMMMMMMm.                                                             `               .MMMMMMMMMM"
echo "MMMMMMMMMMMN,   `                                                    `         `  `    .MMMMMMMMMMMM"
echo "MMMMMMMMMMMMMN,      `                                            `                  ..MMMMMMMMMMMMM"
echo "MMMMMMMMMMMMMMMm,                `  `                 `                 `           .MMMMMMMMMMMMMMM"
echo "MMMMMMMMMMMMMMMMMN,      `    `                    `           `            `    .JMMMMMMMMMMMMMMMMM"
echo "MMMMMMMMMMMMMMMMMMMNJ.                  `   `  `         `  `       `         `.dMMMMMMMMMMMMMMMMMMM"
echo "MMMMMMMMMMMMMMMMMMMMMMN,    `                                          `    .+MMMMMMMMMMMMMMMMMMMMMM"
echo "MMMMMMMMMMMMMMMMMMMMMMMMMNJ.     `  `                `           `      ..gMMMMMMMMMMMMMMMMMMMMMMMMM"
echo "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMNJ.           `      `     `     `     ..+MMMMMMMMMMMMMMMMMMMMMMMMMMMMM"
echo "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNaJ..  `     `            `  ...&MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"
echo "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNgg+...........+ggMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"
